pipeline {
    agent any  // Runs directly on the Jenkins VM

    environment {
        DOCKER_IMAGE = "abkaur95/jenkins-cicd:${BUILD_NUMBER}"
        REGISTRY_CREDENTIALS = credentials('dockerhub')
        GIT_REPO_NAME = "Ci-cd-with-jenkins-and-argocd"
        GIT_USER_NAME = "abkaur"
    }

    stages {

        stage('Checkout') {
            steps {
                sh 'echo passed'
                git branch: 'main', url: 'https://github.com/abkaur/Ci-cd-with-jenkins-and-argocd.git'
                sh 'ls -la' // Check if Jenkinsfile exists
            }
        }

        stage('Build and Test') {
            steps {
                sh '''
                    ls -ltr
                    cd spring-boot-app && mvn clean package
                '''
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh '''
                            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
                            docker build -t ${DOCKER_IMAGE} spring-boot-app  # Specify the correct directory
                            docker push ${DOCKER_IMAGE}
                        '''
                    }
                }
            }
        }

        stage('Update Deployment File') {
            steps {
                withCredentials([string(credentialsId: 'git-hub-token', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                        git config user.email "kaurab@sheridancollege.ca"
                        git config user.name "abkaur"
                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" spring-boot-app-manifests/deployment.yml
                        git add spring-boot-app-manifests/deployment.yml
                        git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                    '''
                }
            }
        }

    } // End of stages
} // End of pipeline








